---
- name: Exercise for setting up a web server in an EC2
  hosts: all
  user: ubuntu
  vars: 
    - ansible_host_key_checking: false   # to skip the user confirmation on SSH authentication
  roles:
  - setup