# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
jobs:
  create_infrastructure:
    docker:
      - image: amazon/aws-cli
    steps:
     - checkout
     - run:  aws cloudformation create-stack --stack-name test --template-body file://template.yml   --region=us-west-2

# Use a package of configuration called an orb.

# Orchestrate or schedule a set of jobs
workflows:
  # Name the workflow "welcome"
  welcome:
    # Run the welcome/run job in its own container
    jobs:
      - create_infrastructure

